### ISSUE TITLE
No SD card is inserted in the switch or it can't be read. Aborting

### ISSUE THREAD

**Issue by synanimate** [lulle2007200/SwitchSDSetup#3] opened 2020-04-03 21:55 UTC
Trying to use through VirtualBox. Script recognises my Switch is RCM - I've tried multiple SDs know to work in multiple formats (FAT32, exfat). Keep getting the same:

_No SD card is inserted in the switch or it can't be read. Aborting_

**Comment by lulle2007200** [comment] 2020-04-04 12:33
That is because you are using a VM. Either use an Ubuntu live CD/USB stick or use a USB SD card adapter instead.

**Comment by synanimate** [comment] 2020-04-05 08:44
Same thing happens using Ubuntu live (USB). I've been able to use it successfully with sd readers, just not the switch itself.

**Comment by lulle2007200** [comment] 2020-04-05 08:54
Did you use a USB 3.0 port? If not, try that.

**Comment by lulle2007200** [comment] 2020-04-07 23:01
Cant reproduce. Closing for now.

**Closed as completed by lulle2007200** 2020-04-07 23:01 UTC
